### ISSUE TITLE
[Test] 3 env vars, no env vars

### ISSUE THREAD

**Issue by marti1125** [carols10cents/cargo-open#2]
Could you explain me more, please? I don't have much experience with Rust =)

**Comment by carols10cents** [comment]
Sure! By this one, I meant to add tests around the behavior of checking the environment variables `$CARGO_EDITOR`, then `$VISUAL`, then `$EDITOR`, stopping and using the value if one is set, and if none of them are set, printing an error that guides the user to setting one. 

I'm actually not sure how I'm going to do tests at all yet-- I'm probably going to model them after [cargo's tests](https://github.com/rust-lang/cargo/tree/master/tests)-- cargo has some nice test helpers and utilities for [setting environment variables for running a process](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/process_builder.rs#L49) and [setting up temporary test projects](https://github.com/rust-lang/cargo/blob/master/tests/support/mod.rs#L204).

Please let me know if you have any more questions!!

**Comment by marti1125** [comment]
ok, I understand. I am going to make a test where check env vars
because by default in Mac is vim editor
example :)
http://stackoverflow.com/questions/25084035/setting-editor-or-bundler-editor-environment-variable

**Comment by marti1125** [comment]
http://stackoverflow.com/questions/27840394/how-can-a-rust-program-access-metadata-from-its-cargo-package

**Comment by marti1125** [comment]
hi @carols10cents any update?

**Comment by carols10cents** [comment]
Oooh I'm so sorry!! I missed your PR for some reason, and then I was out of town... taking a look now!!! :heart_decoration:

**Comment by carols10cents** [comment]
There are now tests for this!!
